'use client'
import { useEffect, useState } from 'react'
type Project={id:string;name:string;goal:string;repositoryPath:string;defaultBranch:string}
type Task={id:number;title:string;objective:string;specification:string;acceptanceCriteria:string[];constraints:string[];dependencies:string[];branch?:string;priority:number;position:number;status:string}
const empty={title:'',objective:'',specification:'',acceptanceCriteria:[],constraints:[],dependencies:[],branch:'',priority:0,position:0} as Omit<Task,'id'|'status'>
export default function Page(){
 const [projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(''),[queue,setQueue]=useState<Task[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[task,setTask]=useState(empty),[editing,setEditing]=useState<number|null>(null),[project,setProject]=useState({name:'',goal:'',repositoryPath:'',defaultBranch:'main'}),[inspection,setInspection]=useState<any>(null),[requestedNumber,setRequestedNumber]=useState('')
 async function request(path:string,method='GET',body?:unknown){const response=await fetch(path,{method,cache:'no-store',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const result=response.status===204?{}:await response.json();if(!response.ok)throw new Error(result.error??'Request failed');return result.data}
 async function perform(action:()=>Promise<void>){setBusy(true);setError('');try{await action()}catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{setBusy(false)}}
 useEffect(()=>{perform(async()=>setProjects(await request('/api/projects')))},[])
 async function loadQueue(id:string){const data=await request(`/api/queue?projectId=${encodeURIComponent(id)}`);setQueue(data)}
 return <main className="page-content" style={{maxWidth:1100,margin:'auto'}}><h1>DEV QUEUE · LOCAL</h1><p>Human defines work. Server authorizes work. Worker executes work. Cline execution remains blocked.</p>
 {error&&<p role="alert">{error}</p>}
 <h2>Projects</h2>{!projects.length&&<p>No projects yet. Create Project (or connect to load existing projects).</p>}
 <label>Project <select value={projectId} onChange={e=>{const id=e.target.value;setProjectId(id);setQueue([]);setInspection(null);setTask(empty);setEditing(null);if(id)perform(()=>loadQueue(id))}}><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
 <form onSubmit={e=>{e.preventDefault();perform(async()=>{const data=await request('/api/projects','POST',project);setProjects(await request('/api/projects'));setProjectId(data.id);await loadQueue(data.id)})}}>{(['name','goal','repositoryPath','defaultBranch'] as const).map(key=><label key={key}>{key}<input required value={project[key]} onChange={e=>setProject({...project,[key]:e.target.value})}/></label>)}<button disabled={busy}>Create Project</button></form>
 {projectId&&<><button disabled={busy} onClick={()=>perform(async()=>{await request(`/api/projects/${encodeURIComponent(projectId)}`,'PATCH',project);setProjects(await request('/api/projects'))})}>Update selected project with fields above</button><button onClick={()=>{const p=projects.find(p=>p.id===projectId);if(p)setProject(p)}}>Load selected project into editor</button>
 <h2>{editing?'Edit':'Create'} PR task</h2><form onSubmit={e=>{e.preventDefault();perform(async()=>{await request(editing?`/api/queue/${editing}`:'/api/queue',editing?'PATCH':'POST',{...task,projectId,...(!editing&&requestedNumber?{number:Number(requestedNumber)}:{})});await loadQueue(projectId);setTask(empty);setEditing(null)})}}>
 {(['title','objective','specification','branch'] as const).map(key=><label key={key}>{key==='specification'?'Specification — implementation requested':key}<textarea required={key==='title'||key==='objective'} value={task[key]??''} onChange={e=>setTask({...task,[key]:e.target.value})}/></label>)}
 {(['acceptanceCriteria','constraints','dependencies'] as const).map(key=><label key={key}>{key==='acceptanceCriteria'?'Acceptance criteria — separate gates (empty means no criteria defined)':key+' (one per line)'}<textarea value={task[key].join('\n')} onChange={e=>setTask({...task,[key]:e.target.value?e.target.value.split('\n'):[]})}/></label>)}
 {(['priority','position'] as const).map(key=><label key={key}>{key}<input type="number" min="0" value={task[key]} onChange={e=>setTask({...task,[key]:Number(e.target.value)})}/></label>)}<label>PR number (optional at creation)<input type="number" min="1" disabled={editing!==null} value={editing??requestedNumber} onChange={e=>setRequestedNumber(e.target.value)}/></label><p>PR number is allocated atomically by the server and shown below; it is not editable after creation.</p><button disabled={busy}>Save task</button></form>
 <h2>Project queue</h2>{!queue.length&&<p>No PRs in this project.</p>}{queue.map((item,index)=><section className="panel" key={item.id} style={{padding:16}}><h3>#{item.id} {item.title} — {item.status}</h3><p>{item.objective}</p><p>Position: {item.position} · Priority: {item.priority} · Dependencies: {item.dependencies.join(", ")||"none"}</p><p>Acceptance criteria: {item.acceptanceCriteria.length?item.acceptanceCriteria.join('; '):'Empty — no gates defined'}</p>{item.status==='failed'&&<button onClick={()=>perform(async()=>{await request('/api/local-actions','POST',{action:'retry',projectId,number:item.id});await loadQueue(projectId)})}>Retry failed task</button>}<button onClick={()=>{setEditing(item.id);setTask(item)}}>Edit</button>{(['up','down'] as const).map(direction=><button key={direction} disabled={busy||(direction==='up'?index===0:index===queue.length-1)} onClick={()=>perform(async()=>{await request(`/api/queue/${item.id}`,'PATCH',{projectId,action:'reorder',direction});await loadQueue(projectId)})}>{direction}</button>)}<button disabled={busy} onClick={()=>{if(confirm(`Delete PR #${item.id}?`))perform(async()=>{await request(`/api/queue/${item.id}?projectId=${encodeURIComponent(projectId)}`,'DELETE');await loadQueue(projectId)})}}>Delete</button></section>)}
 <h2>Worker / Activity / Attention</h2><button disabled={busy} onClick={()=>perform(async()=>setInspection(await request(`/api/inspection?projectId=${encodeURIComponent(projectId)}`)))}>Inspect project execution</button>{inspection?.sessions?.filter((s:any)=>s.status==='waiting').map((s:any)=><section key={s.id}><h3>ATTENTION REQUIRED</h3><p>{s.currentQuestion}</p><button onClick={()=>{const answer=prompt('Answer worker question');if(answer)perform(async()=>{await request('/api/local-actions','POST',{action:'answer',sessionId:s.id,answer});setInspection(await request(`/api/inspection?projectId=${encodeURIComponent(projectId)}`));await loadQueue(projectId)})}}>Answer</button></section>)}<pre style={{whiteSpace:'pre-wrap'}}>{inspection?JSON.stringify(inspection,null,2):'No inspection loaded.'}</pre></>}
 </main>
}
